"""add index

Revision ID: 2adf7786d90f
Revises: 176a9d99c888
Create Date: 2026-06-14 22:49:46.474189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2adf7786d90f'
down_revision = '176a9d99c888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_featured'), ['featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_status'))
        batch_op.drop_index(batch_op.f('ix_listing_price'))
        batch_op.drop_index(batch_op.f('ix_listing_game_id'))
        batch_op.drop_index(batch_op.f('ix_listing_featured'))

    # ### end Alembic commands ###
