"""add index

Revision ID: 3633e1aa7b7b
Revises: 2adf7786d90f
Create Date: 2026-06-22 11:36:20.450030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3633e1aa7b7b'
down_revision = '2adf7786d90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               nullable=False)
        batch_op.alter_column('game_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('seller_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('buy_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.create_index('idx_listing_home', ['status', 'featured', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_sale_type'), ['sale_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_seller_id'), ['seller_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_seller_id'))
        batch_op.drop_index(batch_op.f('ix_listing_sale_type'))
        batch_op.drop_index(batch_op.f('ix_listing_created_at'))
        batch_op.drop_index('idx_listing_home')
        batch_op.alter_column('buy_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('seller_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('game_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               nullable=True)

    # ### end Alembic commands ###
