"""change float to string for price

Revision ID: 800c120be6a8
Revises: db5c344a54ef
Create Date: 2026-05-22 11:33:16.919656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '800c120be6a8'
down_revision = 'db5c344a54ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.String(length=200),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
