"""add sale_type column

Revision ID: 962d8f87d647
Revises: 113c8237c3e7
Create Date: 2026-05-29 12:07:32.470492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962d8f87d647'
down_revision = '113c8237c3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('sale_type')

    # ### end Alembic commands ###
