"""add seller profile fields

Revision ID: 9f4fb4ae5192
Revises: 2a954b6e6a48
Create Date: 2026-05-24 20:35:13.928693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4fb4ae5192'
down_revision = '2a954b6e6a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('telegram', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('messenger', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('viber', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('viber')
        batch_op.drop_column('messenger')
        batch_op.drop_column('telegram')
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
