"""add column to game

Revision ID: efbc8ee55761
Revises: d0d18cf69df7
Create Date: 2026-05-30 20:59:00.185203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efbc8ee55761'
down_revision = 'd0d18cf69df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('messenger', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('viber', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('viber')
        batch_op.drop_column('messenger')
        batch_op.drop_column('telegram')

    # ### end Alembic commands ###
