"""added financial fields

Revision ID: f381a2ac9ff8
Revises: 9f4fb4ae5192
Create Date: 2026-05-25 21:06:26.441742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f381a2ac9ff8'
down_revision = '9f4fb4ae5192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buy_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sold_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('sold_price')
        batch_op.drop_column('buy_price')

    # ### end Alembic commands ###
